### ISSUE TITLE
Departure board prevent full speed fast forward

### ISSUE THREAD

**Issue by innocenat** [JGRennison/OpenTTD-patches#119]
## Version of OpenTTD
aa8aae9a

## Expected result
Fast fast forward

## Actual result
Slower fast forward

## Steps to reproduce

1. Open departure board with train on the board, with scrolly Calling at: animation
2. Try to fast forward, compared with without the departure board open.

**Comment by auge8472** [comment]
This works (in my humble opinion) as designed. The fast forward works as fast it can on the machine and with the (in the concrete situation) necessary computings. If you do something that makes additionally calculations necessary, the fast forward will slow down because the computer has to fulfill additionally tasks.

**Comment by innocenat** [comment]
I believe the new fast fast-forward is going everything as fast as possible without actually drawing everything to the screen. So if animation make it slower (and it is much slower, like 10 times slower on my ultrabook machine), it doesn't sounds like it works as designed for me.

**Comment by JGRennison** [comment]
Excessive use of GetStringBoundingBox and always redrawing the whole display pane every tick look like the main culprits.
