### ISSUE TITLE
Multiplayer Version Conflict

### ISSUE THREAD

**Issue by TheNewCivilian** [JGRennison/OpenTTD-patches#20]
Compiled and ran the Patch on Windows, MacOS and Linux (Ubuntu) separately. Unfortunately I couldn't connect from ether MacOS or Windows to the Server (Started on Linux). => Version Conflict O.o Is there a way to avoid this by editing some config File etc.

**Comment by JGRennison** [comment]
This is probably because the server and clients are at different versions (different commit IDs).
Alternatively, the copy of the code you have may on one or more of your builds may be locally modified, which changes the version string.
The version string can be found by running `findversion.sh` and looking at the first field, or by looking in the title bar when running it.

**Comment by mvolfik** [comment]
Please visibly mention this in README...
