### ISSUE TITLE
Dynamicly compiled releases aren't portable

### ISSUE THREAD

**Issue by haydenhv** [JGRennison/OpenTTD-patches#234]
## Version
0.40.5-linux-generic-amd64
(it is not actually generic, though)

## Expected result
Binaries should just run, regardless of the availability of specific libraries.

## Actual result
/bin/ksh: ./openttd-jgrpp-0.40.5-linux-generic-amd64/openttd: No such file or directory
(it is there)
An ldd of the file shows plenty of missing symbols

## Steps to reproduce
Attempt to run JGRPP on any distribution that doesn't have the expected files in /lib,
for example, any system that uses musl instead of glibc.

**Comment by embeddedt** [comment]
https://github.com/OpenTTD/OpenTTD/pull/8641

> Machines needs at least glibc 2.15, which was released 10 years ago.

If JGR is using the same build logic, it sounds like this might be intended.

**Comment by JGRennison** [comment]
Yes, the CI/build configuration is the same as that of upstream.
You could try raising an issue with them.

Due to the extreme diversity of distros, it's nearly impossible to build a single statiic binary which works absolutely everywhere and includes any sort of GUI functionality.
You're probably better off compiling from source and/or trying to get someone from whatever distro that you're using to package it.
