### ISSUE TITLE
Crash if I use Korean Signal Set

### ISSUE THREAD

**Issue by telk5093** [JGRennison/OpenTTD-patches#255]
## Files
Crashlog: [crash.zip](https://github.com/JGRennison/OpenTTD-patches/files/6446061/crash.zip)
Savegame: [20210509_0006.zip](https://github.com/JGRennison/OpenTTD-patches/files/6446062/20210509_0006.zip)

## Screenshots
![image](https://user-images.githubusercontent.com/10726524/117544369-21792780-b05c-11eb-8e03-0d05040eb5c3.png)

This map is a save file of my multiplayer game that is run at jgrpp-0.41.0.
I doubted that it is related to newgrf and I found that it crashes if I use ``Korean Signal Set 1.0.3``.
Note that I've tried to start a new map without newgrf at all (works) and with Korean Signal Set only (crashed)
If I load the savegame file above at jgrpp-0.41.0, it works fine.

## Version of OpenTTD
jgrpp-0.41.1

## Steps to reproduce
Load this save with ``Korean Signal Set 1.0.3``

**Comment by JGRennison** [comment]
The asserts are a bit unnecessary. I will replace these with a warning message to the console instead.

The issue is related to the NewGRF, it is not implemented correctly.
In the current upstream master (nightly builds, etc.). it shows the wrong signal sprites and overwrites the sprite IDs now used in the new multiplayer client window.
In upstream 1.10 and previous it also shows the wrong signal sprites.

Using `replace` in NML is only valid for the fixed original sprite IDs, see: https://newgrf-specs.tt-wiki.net/wiki/NML:Replace_TTD_sprites

You should use `replacenew` instead, see: https://newgrf-specs.tt-wiki.net/wiki/NML:Replace_new_sprites

**Comment by telk5093** [comment]
Thanks for letting me know, I have to rework this grf then.
btw, how can I replace programmable signals then?

**Comment by JGRennison** [comment]
You can use my NML fork here: https://github.com/JGRennison/nml
It adds support for setting programmable signal sprites as per here: https://htmlpreview.github.io/?https://github.com/JGRennison/OpenTTD-patches/blob/jgrpp/docs/newgrf-additions-nml.html
The output GRF does the right thing when loaded in trunk or other versions.
