### ISSUE TITLE
Suggestion/Unintuitive controls

### ISSUE THREAD

**Issue by VacuumBreather** [JGRennison/OpenTTD-patches#294]
Currently you can open the signal progam window of a programmable presignal by Ctrl-Clicking it. However you cannot do the same with all the other signals to assign a tracing restriction to them. This feels unintuitive and is also probably a feature needed more since the tracing programs are used way more often.

**Comment by JGRennison** [comment]
The original motivation for this feature is spectator mode.
The signal window is not available when spectating and otherwise there is no way to observe the state of a programmable pre-signal program, or a routing restriction program.
Any signal, including programmable pre-signals, may have a routing restriction program attached. Ctrl-clicking will open both if they are both present.
I'll look into modifying this.

**Comment by VacuumBreather** [comment]
Sure but it's still super nice if you can open it like that to quickly check something :)

**Comment by VacuumBreather** [comment]
Shouldn't this be closed now since you added that functionality?

**Comment by JGRennison** [comment]
Probably a good idea, closing now...
