### ISSUE TITLE
Bug Report - Separate Purchase Window for Engines and Wagons shows Incorrect Engine Capacities instead of N/A

### ISSUE THREAD

**Issue by reldred** [JGRennison/OpenTTD-patches#296]
## Version of OpenTTD
0.42.0

## Expected result
Expect the Capacity: field on Engines to show N/A

## Actual result
Shows an amount of passengers.

## Steps to reproduce
Enable feature

Regular Window:
![image](https://user-images.githubusercontent.com/19522569/124482019-06baf900-dde8-11eb-8baf-16b4892651a0.png)

Separated Window:
![image](https://user-images.githubusercontent.com/19522569/124482130-205c4080-dde8-11eb-854b-f954b96e4fd3.png)

**Comment by James103** [comment]
This also happens the other way around. To reproduce:
1. Start a game in the year 2000 without any NewGRFs loaded.
2. Open the company's train listing, then click "Available Trains".
3. Under "Wagons", filter by cargo type "None".
4. Under "Locomotives and Power Cars", select for example "Dash" engine.
5. Select, for example "Mail Van".
6. It incorrectly says that the wagon can carry 80 passengers, instead of the expected 30 bags of mail.

**Comment by JGRennison** [comment]
Should be fixed by 5230ff5

**Comment by Gugui322** [comment]
![Chaos Transport Co, 20 Mai 1957](https://user-images.githubusercontent.com/65572156/124615589-cc834300-de4b-11eb-8af2-b2bbcbb29f2b.jpg)

Very strange behavior.

**Comment by JGRennison** [comment]
This should be fixed in 0.42.3
