### ISSUE TITLE
Drive-Through depots not working

### ISSUE THREAD

**Issue by wpas81** [JGRennison/OpenTTD-patches#304]
hi

1st of all: great work! This is a huge improvement to the regular version. But I don't seem to make the drive-through depots work. Also can't find a setting for it.

**Comment by embeddedt** [comment]
I believe that there is a setting you have to enable. Check that you are in expert mode in the settings window, otherwise some settings are hidden.

**Comment by wpas81** [comment]
You're right... I did turn it on in the settings but didn't read the description... "Trains can move between depots placed back to back" . I placed multiple in the same direction... My bad.Thanks!

**Comment by wpas81** [comment]
OK one more remark. I made a test-track. It works when I have one drive-through depot. If I put a second one on the same track it doesn't seem to move through them anymore. But I guess I can work with it now. Great work in your patch! Wouldn't want to miss it anymore

**Comment by JGRennison** [comment]
At present the pathfinder will not look through drive-through depots, as a valid path to get to somewhere else, this is partly so that drive through depots do not become shortcuts which attract non-depot traffic.
Probably if you have multiple drive-through depots one after the other the pathfinder cannot find the destination.

**Comment by reldred** [comment]
I've not run into many issues with this just as an FYI; I routinely build my drive through depots four to seven tiles long. What I normally do is align them like so <<<>>>> for a seven tile for instance.
