### ISSUE TITLE
[Bug]: "?" in config file for extra_display_opt

### ISSUE THREAD

**Issue by EratoNysiad** [JGRennison/OpenTTD-patches#344]
### Version of OpenTTD

0.44.2, Windows

### Expected result

The settings are good and I get no error popup at the beginning of the game.

### Actual result

![image](https://user-images.githubusercontent.com/10280358/147239001-17aa5179-2b7b-4ed5-847a-dd1169c60512.png)
I get this, instead of nothing

### Steps to reproduce

1. Open JGR
2. This pops up at the main menu
3. config file shows '?' for some reason

**Comment by James103** [comment]
1. What happens if you rename or move `openttd.cfg` to something else in order to let OpenTTD generate a new config file on boot? Do you get the same error?
2. Rename/move the original `openttd.cfg` so as to overwrite the newly generated file with the same name, then relaunch OpenTTD. Do you get a similar error?

**Comment by EratoNysiad** [comment]
1. That takes care of the error, and it no longer appears
2. `extra_display_opt = p?` is still in the config, so it still shows it.

Having not edited the config file, I don't know how this got in a second time. I thought it had something to do with booting the basegame but no.

**Comment by James103** [comment]
Try deleting the line `extra_display_opt = p?` from openttd.cfg and then rebooting. Do you get the same error?

**Comment by JGRennison** [comment]
I've reproduced this here and upstream.
In the meantime turn income texts back on to avoid extra_display_opt being empty.
I'll create an issue upstream shortly.
