### ISSUE TITLE
[Bug]: Train braking with Realistic Braking on is paused when Improved Brakedowns' "Reduced Speed" breakdown happens.

### ISSUE THREAD

**Issue by geby** [JGRennison/OpenTTD-patches#345]
### Version of OpenTTD

JGRPP 0.44.0

### Expected result

Brake down even when it cannot go faster.

### Actual result

Braking down is stopped (e. g. train continues without changing speed) when the "Reduced speed" brakedown is active, and continues braking after breakdown is "solved".

### Steps to reproduce

[autosave3.zip](https://github.com/JGRennison/OpenTTD-patches/files/7777185/autosave3.zip)

1. Open Save.
2. Look inside of vehicle lists for Blue company's train no. 7 and open small Vehicle Info window.
3. Unpause.
4. Wait until it comes at big drive-through station. (at my end it always produced the same breakdown when aproaching that station)

**Comment by JGRennison** [comment]
It seems that when the breakdown occurs when pulling up to the station the train temporarily changes order to a depot for servicing, because the service at order is missing from the order list. I will see if that servicing behaviour can be adjusted.

In general, each order list should have at least one service or go to depot order.
There's a news setting "Warn if a vehicle does not have a depot order in its schedule" which should be switched on which warns when this is missing.

**Comment by geby** [comment]
I always learn new stuff. :-)
I did play this game whole time in way, that trains go to depot when they decide to, and put depots at good places for it. I have however not used the explicit service, but I will do it from now...
