### ISSUE TITLE
Payments for delivery of transferred cargo

### ISSUE THREAD

**Issue by RoqueDeicide** [JGRennison/OpenTTD-patches#35]
When the vehicle (tried it with ships and trains) delivers cargo it had transferred from another vehicle to its final destination, the money from the delivery seems to get onto the bank account fine, but it doesn't get registered properly by the vehicle itself, leading to "negative income" from the delivery.

**Comment by auge8472** [comment]
That's normal behaviour of OpenTTD when freight or passengers use more than one vehicle to reach its destination (with or even without CargoDistribution). Because of the assignment of the income to the different vehicles it is possible, that the whole income get assigned to the first vehicle(s) of the chain so the income of the last vehicle is to small to cover its costs. That's the reason, you see the red, negative income.

You can work against it somewhere in the settings but at the moment I can't tell you, where to search.

**Comment by RoqueDeicide** [comment]
OK, I did some more testing and this issue is, apparently, with FIRS, since everything is fine with default industries. Sorry for bother.
