### ISSUE TITLE
[Bug]: Automatet Timetables waiting at Stations up to 94 minutes

### ISSUE THREAD

**Issue by Micesebi** [JGRennison/OpenTTD-patches#557]
### Version of OpenTTD

0.54.2, Arch Linux

### Expected result

Automated Timetables creating reasonable Timetables for my Passenger Trains 

### Actual result

Stops are being scheduled with 10-94 minutes waiting time, happens at random times at random stations to random extends. started recently and also happen with only 1 train per line while troubleshooting. Mainly observed with GETS 3.0 and not yet on other savefiles.

![pastime](https://github.com/JGRennison/OpenTTD-patches/assets/118563234/4c8a84ed-b243-4e0c-b2c6-359e30985a5b)

### Steps to reproduce

[German Realaty.zip](https://github.com/JGRennison/OpenTTD-patches/files/11871343/German.Realaty.zip)

1. Load save file
2. Buy/Observe Passenger Trains at Stations

**Comment by James103** [comment]
Do you have "full load" or "full load any cargo" orders on the affected trains?

**Comment by JGRennison** [comment]
Your trains are longer than your stations, this adds a very significant time penalty to loading/unloading.
The timetable automation is adjusting the timetable due to the delay, it isn't the cause of the delay.

You should make your stations longer or shorten your trains, such that they fit completely in all stations on their route.
