### ISSUE TITLE
Suggestion/Question: Am I able to create "or/else" statements in conditional train orders?

### ISSUE THREAD

**Issue by NicholasRB** [JGRennison/OpenTTD-patches#608]
I've come across a unique situation where I have a trains that share a schedule acting as real life manifests (trains that just go from yard to yard). In game they go from yard station to yard station to bulk transfer cargo easier then running each individual train back and forth. So after fiddling around with the conditional orders and such, I realized very quickly there is no way that I know of making an "else" statement like signals allow us to do. Everything in a train's orders acts as an "and" command with no way of changing that.

I want to make it so if anything that heads to the station (Birmingham is Chemicals, Machines & eventually Scrap Metal. Dover is Metal and Oil) is waiting in the station to be picked up, the train heads to that station. Currently what happens is the train just gets stuck on the 1st order or whatever order is not able to be fulfilled just staying in the depot the whole time and not even caring about the rest of the cargos I put in the schedule.
![Pennsylvania, Reading   Pacific, 1958-11-10](https://github.com/JGRennison/OpenTTD-patches/assets/45899940/a0b0ad3e-4901-49e5-9756-306b81d67eb6)

**Comment by JGRennison** [comment]
In general the "else" case is the order immediately after a jump.
"Or" type functionality is just another conditional jump with the same target.

I'm not really sure what the order list is trying to do, but for example:
Order 5 does nothing and can be removed.
Order 14 can be replaced with an unconditional jump (because of order 13), so order 15 therefore does nothing, so orders 14 and 15 can both be removed.

**Comment by NicholasRB** [comment]
Ah okay that makes sense. Thanks!
