### ISSUE TITLE
Bad utilization of resources (?)

### ISSUE THREAD

**Issue by Carbonatek** [JGRennison/OpenTTD-patches#79]
Version of OpenTTD: OpenTTD jgrpp-0.29.3

Hello there,
when I tried to generate a 16384x16384 world, I noticed that my game is constantly spiking, which is a understatement. But, what surprised me, is the high RAM usage (still understandable) but the CPU usage is only on one core (I have a quad core - http://prntscr.com/n01sj6). Wouldn't be better to somehow manage to force OpenTTD to use two, or more cores? It would improve generating times significantly. Also, the time I am writing this, the world is generating for like a century (also known as fifteen minutes).

**Comment by auge8472** [comment]
The single core mode is a core "feature" of OpenTTD itself. This is because OpenTTD works with an architecture from the 1990-ies where multicore processors and mainboards was an almost exclusive domain of servers and not of personal computers. OpenTTD works massively with timing functions which would fail in multicore mode so it ustilises only one core (with a very few exceptions (as far as I know)).
